### ISSUE TITLE
HTML parser is getting the wrong column.

### ISSUE THREAD

**Issue by marcelocastrobarbosa** [whateverpal/coinmetrics-tools#1]
For instance, for price(usd) it is bringing volume, for marketcap(usd) it is getting prices.

**Comment by whateverpal** [comment]
Hello, mcbarb, the issue is a bit unclear. As far as I can see, the order of data types in CSV header matches the order used by rows in CSV body.

**Comment by whateverpal** [comment]
Closing due to issue being unclear and the absence of reporter's response
